import type { Metadata } from "next";
import {
  Alegreya,
  Geist,
  Geist_Mono,
  IM_Fell_English_SC,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const diceDisplay = IM_Fell_English_SC({
  variable: "--font-dice-display",
  weight: "400",
  subsets: ["latin"],
});

const diceBody = Alegreya({
  variable: "--font-dice-body",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${diceDisplay.variable} ${diceBody.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
